### ISSUE TITLE
OutputFile error

### ISSUE THREAD

**Issue by liuzhuonan** [mzohaibqc/antd-theme-generator#1]
This is the outputFile.![image](https://user-images.githubusercontent.com/23043832/41089174-c74d186a-6a73-11e8-8e62-90ce3ad94550.png)

And this is the original.
![image](https://user-images.githubusercontent.com/23043832/41089228-f367470e-6a73-11e8-94cf-c51803158495.png)
Is it a problem?

**Comment by bluesh** [comment]
Because your color has same value, maybe

**Comment by mzohaibqc** [comment]
Try updating to latest version. At the time of writing, it is `antd-theme-generator@1.1.6`
