### ISSUE TITLE
antd after update to 4.17.2， generatorTheme will report Error 

### ISSUE THREAD

**Issue by cl1107** [mzohaibqc/antd-theme-generator#100]
**Describe the bug**
antd updated to 4.17.2， generatorTheme will report  Error: ENOENT: no such file or directory, open '{folder}/node_modules/antd/lib/style/themes/@{root-entry-name}.less'

**Comment by yuepu** [comment]
me,too

`"antd": "^4.15.5",`

**Comment by daichuqi** [comment]
+1

**Comment by cl1107** [comment]
temporary fix： node_modules/less-bundle-promise/lib/buildcontents.js  line 32
add hashPath = hashPath.replace(/@{root-entry-name}/g, 'default');
![image](https://user-images.githubusercontent.com/21985353/143991968-5f4a3922-9990-44c6-8915-cc11a3cfec5c.png)

**Comment by ghost** [comment]
same here

**Comment by rafaelncarvalho** [comment]
I have the same problem too

**Comment by wkylin** [comment]
I have the same problem too

**Comment by yudidayeye** [comment]
+1

**Comment by iaminnasr** [comment]
same here

**Comment by zhanghui-space** [comment]
+1

**Comment by mzohaibqc** [comment]
@cl1107 @yuepu @daichuqi @aniznik1 @rafaelncarvalho @yudidayeye @iaminnasr @gzhanghui 
This issue has been fixed in version 1.2.11

Install new version `antd-theme-generator@1.2.11`
