### ISSUE TITLE
Bug report: themeVariables cannot support @body-background and @component-background

### ISSUE THREAD

**Issue by blackcater** [mzohaibqc/antd-theme-generator#19]
When I set `themeVariables` to `['@body-background']` or `['@component-background']`.

It will report a bug in Developer Tools.

![image](https://user-images.githubusercontent.com/9465551/52837821-4c999880-312b-11e9-9f0b-c21c5d91031d.png)

When I use `@body-background`, `color.less` file will contain `@body-backgroundbe6`.

![image](https://user-images.githubusercontent.com/9465551/52837932-c9c50d80-312b-11e9-8bd7-f65c5a5a04e3.png)

When I use `@component-background`, `color.less` file will contain `@component-backgroundbe6`

**Comment by mzohaibqc** [comment]
@blackcater Can you create a repo and reproduce this so I can look into that

**Comment by blackcater** [comment]
> @blackcater Can you create a repo and reproduce this so I can look into that

[Here is a repo](https://github.com/blackcater/antd-theme-generator--19).

It's my fault. I cannot find the below tips.

> Note: include all color variables in varFile that you want to change dynamically and assign them unique color codes. Don't assign same color to two or more variables and don't use #fff, #ffffff, #000 or #000000. If you still want white or black color as default, slightly change it e.g. #fffffe or #000001 which will not replace common background colors from other components.

I will close this issue.

Thanks a lot.

**Comment by mzohaibqc** [comment]
@blackcater Thanks for your comment. It will help other users to avoid such situation.
