### ISSUE TITLE
The generated color.less is not correct if two color variables are same.

### ISSUE THREAD

**Issue by gaohuijue** [mzohaibqc/antd-theme-generator#2]
https://github.com/mzohaibqc/antd-theme-generator/blob/aa5a08baec241775f63e7b0eba38a9014f1e6f04/index.js#L326

variables.less
```
@import "../../../../../node_modules/antd/lib/style/themes/default";
@primary-color: #ff2a00;
@btn-primary-bg: #ff2a00;// Same as primary-color
```
color.less
```
...
a {
  color: @btn-primary-bg;
  background-color: transparent;
}
...
```

Sory,my English is poor.
I think you may warn developers notify this.Tell them not set same color value.

**Comment by mzohaibqc** [comment]
@gaohuijue You are right. Assigning same default value to color variables does not work. I'll add this in documentation
