### ISSUE TITLE
[support] Can we support other variables ( such as: @border-radius-base) ?

### ISSUE THREAD

**Issue by hong-boy** [mzohaibqc/antd-theme-generator#22]

**Comment by chentianxin** [comment]
https://github.com/ant-design/ant-design/blob/master/components/style/themes/default.less

**Comment by mzohaibqc** [comment]
@hong-boy @chentianxin 
Not sure but this might be achieved but it will require a complete rewrite or at least will require a different approach to get this done. I'll try to do this on weekends.

**Comment by mzohaibqc** [comment]
Not in scope

**Comment by anuragguptanbmc** [comment]
@mzohaibqc Can you please guide on how this can be achieved? I will try to write a new plugin if needed.
