### ISSUE TITLE
mainLessFile是文件路径字符串，那generateColorMap(mainLessFile)什么也得不到

### ISSUE THREAD

**Issue by us6002** [mzohaibqc/antd-theme-generator#24]
https://github.com/mzohaibqc/antd-theme-generator/blob/fb7540449f4c372f84f7339c18fb60210785e99e/index.js#L315

mainLessFile是文件路径字符串，那generateColorMap(mainLessFile)不会返回什么，生成不了自定义ColorMap。

"mainLessFile" is just a path string, So `generateColorMap(mainLessFile)` would not return the colorMap of your own variables.less

**Comment by senwong** [comment]
I hava same problem

**Comment by mzohaibqc** [comment]
I don't understand Chinees language so kindly mention your issue in English.
