### ISSUE TITLE
执行多次最后编译生成的color.less越来越大，不是完全覆盖原来的吗？

### ISSUE THREAD

**Issue by cszo** [mzohaibqc/antd-theme-generator#25]
if (outputFilePath) {
          fs.writeFileSync(outputFilePath, css);
          console.log(
            `🌈 Theme generated successfully. OutputFile: ${outputFilePath}`
          );
        } else {
          console.log(`Theme generated successfully`);
        }
        cssCache = css;
        return resolve(css);
      })

**Comment by mzohaibqc** [comment]
@cszo Kindly translate the heading into English for all others who have a similar issue. I'll translate and will look into this,

**Comment by youyeke** [comment]
you can try:
```
const path = require('path');
const fs = require('fs');
const { generateTheme } = require('antd-theme-generator');

fs.unlinkSync(outputFilePath); // remove it first
```

**Comment by mzohaibqc** [comment]
One can just get the generated less output and then write into a file of your own choice.
