### ISSUE TITLE
Theme switching cannot modify colors using fade method

### ISSUE THREAD

**Issue by qizhancheng** [mzohaibqc/antd-theme-generator#27]
Theme switching cannot modify colors using fade method

[https://github.com/ant-design/ant-design/issues/20079](https://github.com/ant-design/ant-design/issues/20079)

**Comment by mzohaibqc** [comment]
No, you need to choose unique color values like this `#ccdddd` containing 6 hex values. You can calculate the color in some online less console/playground and the use that color in your code.
