### ISSUE TITLE
window.less.modifyVars is not working in sometimes

### ISSUE THREAD

**Issue by LXIACHUA** [mzohaibqc/antd-theme-generator#28]
When I set the color of layout-header-background in variables.less，then window.less.modifyVars({'@layout-header-background':'#124fff'}) didn't work. The same thing happened at @text-color.
<img width="275" alt="_20191206162829" src="https://user-images.githubusercontent.com/42471384/70308249-c67b4980-1845-11ea-9a3d-618efe2690d2.png">
<img width="279" alt="_20191206162851" src="https://user-images.githubusercontent.com/42471384/70308259-ced38480-1845-11ea-85f3-f528047f0d4c.png">

**Comment by mzohaibqc** [comment]
@LXIACHUA Use *6* character *unique* color codes only. it does not work well with color names and 3 character color codes like #ccc. I hope this will fix your problem.

**Comment by ccloveak** [comment]
你这个后来怎么解决的啊 我只能改antd的 @primary-color 我自己的样式 加上@primary-color 只能取到编译时候的值 。。。。跪求

**Comment by mzohaibqc** [comment]
@ccloveak Are you facing any issue? I tried to underterstand by using Google translate but can you explain what's the issue you are facing.

**Comment by ccloveak** [comment]
@mzohaibqc Thank you for your reply. I have a requirement for a dynamic theme color change. If I write style code like `color:@primary-color` on `*.module.less`, I can't dynamically change the color of this part. Do you have any ideas? Now I'm writing code like this 
1. 
![image](https://user-images.githubusercontent.com/38686314/107781360-2abf6480-6d8b-11eb-934c-cec4353f844c.png)
2. 
![image](https://user-images.githubusercontent.com/38686314/107781450-41fe5200-6d8b-11eb-970e-5f7e94637782.png)
3. 
![image](https://user-images.githubusercontent.com/38686314/107781651-770aa480-6d8b-11eb-8114-afe452ac2963.png)

It works but not elegant.

**Comment by BWmelon** [comment]
> @mzohaibqc Thank you for your reply. I have a requirement for a dynamic theme color change. If I write style code like `color:@primary-color` on `*.module.less`, I can't dynamically change the color of this part. Do you have any ideas? Now I'm writing code like this 1. ![image](https://user-images.githubusercontent.com/38686314/107781360-2abf6480-6d8b-11eb-934c-cec4353f844c.png) 2. ![image](https://user-images.githubusercontent.com/38686314/107781450-41fe5200-6d8b-11eb-970e-5f7e94637782.png) 3. ![image](https://user-images.githubusercontent.com/38686314/107781651-770aa480-6d8b-11eb-8114-afe452ac2963.png)
> 
> It works but not elegant.

Same problem, did you solve it?
