### ISSUE TITLE
defined a variable caused other components style changed

### ISSUE THREAD

**Issue by yangzhennupt** [mzohaibqc/antd-theme-generator#29]
I defined some variables [ '@primary-color',
    '@text-color',
    '@label-color',
    '@component-background',
    '@border-color-base',
    '@item-active-bg',
    '@tabs-card-head-background',
    '@tabs-card-active-color'] in options to change;
and  also defined in variables.less.

when Theme generated, I found that most components like Select‘s style also changed。
 
I find some unintelligible thing in color.less
```
.ant-select-dropdown-menu-item:hover:not(.ant-select-dropdown-menu-item-disabled) {
  background-color: color(~`colorPalette("@{tabs-card-active-color}", 1)`);
}
```
I think  '@tabs-card-active-color' should not be here， '@select-item-active-bg' is expected

if someone else had this problem ? 

Looking forward to your reply

**Comment by mzohaibqc** [comment]
Do you have unique values for your variables?
