### ISSUE TITLE
当加入@body-background替换颜色时，将Button以及其他组件的color替换为@body-background

### ISSUE THREAD

**Issue by zhang704** [mzohaibqc/antd-theme-generator#31]
![image](https://user-images.githubusercontent.com/18161513/71871987-0049b380-3156-11ea-8614-ac8b14c524da.png)
themeVariables: [
    '@primary-color',
    "@text-color",
    "@heading-color",
    "@text-color-secondary",
    "@disabled-color",
    "@body-background",
  ]

**Comment by mzohaibqc** [comment]
Explain your problem first.

**Comment by zhang504988670** [comment]
当背景色替换为黑色时，Antd Button的字体颜色也随之改变为背景色的颜色（黑色），那样应该是不正确的。
查看编译出来的color.less文件，发现其中很多组件的样式颜色都替换成了@body-backgroud。
正确的不应该是当替换@body-backgroud时，只替换body里的颜色值吗？
