### ISSUE TITLE
It breaks back-top

### ISSUE THREAD

**Issue by NitroBAY** [mzohaibqc/antd-theme-generator#38]
It produces an ".ant-back-top-icon" with a background whose last characters are 1% no-repeat instead of 100%/100% no-repeat

**Comment by mzohaibqc** [comment]
You should have spend few minutes to describe your problem instead of just two lines. No one can understand what are you talking about

**Comment by NitroBAY** [comment]
I use this package and when I call   window.less.modifyVars() the CSS injected into the browser is invalid : there is a rule for ".ant-back-top-icon" which instead of having its background property set to `url(data:image`theimagedata`100%/100% no-repeat)` it is being set to `url(data:image`theimagedata`1% no-repeat)`
SO this package does properly set the background property of ".ant-back-top-icon" as it replaces the end of its value by "1%" instead of 100%/100%.
Which breaks the background of the component.
PS : I am trying to help this project by reporting this issue (not in my mother tongue and web development being something I taught myself) no need for agressivity or hyperbole there are more neutral way to ask me to rephrase the issue. Expressing your frustration is not helpful.

**Comment by mzohaibqc** [comment]
@NitroBAY I've fixed this issue and now all css statements matching `/url\(.*\)/g` will be removed so you will not face this issue again.
Install latest package from npm which is 
`ant-theme-generator@1.2.1`
`antd-theme-webpack-plugin@1.3.2`

**Comment by mzohaibqc** [comment]
Fixed and closed
