### ISSUE TITLE
customColorRegexArray doesn't works

### ISSUE THREAD

**Issue by hellomrbigshot** [mzohaibqc/antd-theme-generator#39]
I try to replace [@primary-1](https://github.com/ant-design/ant-design/blob/master/components/style/themes/default.less)，in  ```Antd``` it shows like
```
@primary-1: color(~`colorPalette('@{primary-color}', 1) `);
```
i try to replace it to ```#111```, so i set
```
customColorRegexArray: [/^color\(.*\)$/]
```
and 
```
window.less.modifyVars({
  '@primary-1': '#111',
  '@primary-color': '#eee',
  ...
})
```
but this color doesn't change.
Other normal color like @primary-color changes.

**Comment by mzohaibqc** [comment]
@hellomrbigshot Show me your configuration options, seems like you are not passing `@primary-1` in themeVariables.

```
const options = {
  antDir: path.join(__dirname, './node_modules/antd'),
  stylesDir: path.join(__dirname, './src/styles'),
  varFile: path.join(__dirname, './src/styles/variables.less'), // default path is Ant Design default.less file
  mainLessFile: path.join(__dirname, './src/styles/index.less'),
  

> themeVariables: ['@primary-1'],

  outputFilePath: path.join(__dirname, './public/color.less') // if provided, file will be created with generated less/styles
  customColorRegexArray: [/^fade\(.*\)$/], // An array of regex codes to match your custom color variable values so that code can identify that it's a valid color. Make sure your regex does not adds false positives.
}

```

**Comment by hellomrbigshot** [comment]
My options
```
const lightTheme = {
  '@primary-color': '#1890ff', // 全局主色
  '@primary-1': '#e6f7ff', // primary-1
  '@link-color': '#1890ff', // 链接色
  '@success-color': '#52c41a', // 成功色
  '@warning-color': '#faad14', // 警告色
  '@error-color': '#f5222d', // 错误色
  '@heading-color': 'rgba(0, 0, 0, 0.85)', // 标题色
  '@text-color': 'rgba(0, 0, 0, 0.65)', // 主文本色
  '@text-color-secondary': 'rgba(0, 0, 0, 0.45)', // 次文本色
  '@disabled-color': 'rgba(0, 0, 0, 0.25)', // 失效色
  '@border-color-base': '#d9d9d9', // 边框色
  '@box-shadow-base': '0 2px 8px rgba(0, 0, 0, 0.15)', // 浮层阴影
  '@component-background': '#fff',
  '@item-hover-bg': '#f5f5f5'
}
const themeVariables = Object.keys(lightTheme)

const options = {
  stylesDir: path.join(__dirname, './src/styles'),
  antDir: path.join(__dirname, './node_modules/antd'),
  varFile: path.join(__dirname, './src/styles/vars.less'),
  mainLessFile: path.join(__dirname, './src/styles/main.less'),
  themeVariables: themeVariables,
  indexFileName: 'index.html',
  outputFilePath: path.join(__dirname, './public/color.less'),
  customColorRegexArray: [/^color\(.*\)$/]
}

```

**Comment by mzohaibqc** [comment]
@hellomrbigshot `themeVariables` is an array of variable names not the object.  you can  use `Objects.keys(themeVariables)` to get array of keys (variable names)

```
const lightTheme = {
  '@primary-color': '#1890ff',
  '@primary-1': '#e6f7ff',
  '@link-color': '#1890ff',
  '@success-color': '#52c41a',
  '@warning-color': '#faad14',
  '@error-color': '#f5222d',
  '@heading-color': 'rgba(0, 0, 0, 0.85)',
  '@text-color': 'rgba(0, 0, 0, 0.65)',
  '@text-color-secondary': 'rgba(0, 0, 0, 0.45)',
  '@disabled-color': 'rgba(0, 0, 0, 0.25)',
  '@border-color-base': '#d9d9d9',
  '@box-shadow-base': '0 2px 8px rgba(0, 0, 0, 0.15)',
  '@component-background': '#fff',
  '@item-hover-bg': '#f5f5f5'
}
const themeVariables = Object.keys(lightTheme)

const options = {
  stylesDir: path.join(__dirname, './src/styles'),
  antDir: path.join(__dirname, './node_modules/antd'),
  varFile: path.join(__dirname, './src/styles/vars.less'),
  mainLessFile: path.join(__dirname, './src/styles/main.less'),
  themeVariables: Objects.keys(themeVariables),
  indexFileName: 'index.html',
  outputFilePath: path.join(__dirname, './public/color.less'),
  customColorRegexArray: [/^color\(.*\)$/]
}
```

**Comment by hellomrbigshot** [comment]
> @hellomrbigshot `themeVariables` is an array of variable names not the object. you can use `Objects.keys(themeVariables)` to get array of keys (variable names)
> 
> ```
> const lightTheme = {
>   '@primary-color': '#1890ff',
>   '@primary-1': '#e6f7ff',
>   '@link-color': '#1890ff',
>   '@success-color': '#52c41a',
>   '@warning-color': '#faad14',
>   '@error-color': '#f5222d',
>   '@heading-color': 'rgba(0, 0, 0, 0.85)',
>   '@text-color': 'rgba(0, 0, 0, 0.65)',
>   '@text-color-secondary': 'rgba(0, 0, 0, 0.45)',
>   '@disabled-color': 'rgba(0, 0, 0, 0.25)',
>   '@border-color-base': '#d9d9d9',
>   '@box-shadow-base': '0 2px 8px rgba(0, 0, 0, 0.15)',
>   '@component-background': '#fff',
>   '@item-hover-bg': '#f5f5f5'
> }
> const themeVariables = Object.keys(lightTheme)
> 
> const options = {
>   stylesDir: path.join(__dirname, './src/styles'),
>   antDir: path.join(__dirname, './node_modules/antd'),
>   varFile: path.join(__dirname, './src/styles/vars.less'),
>   mainLessFile: path.join(__dirname, './src/styles/main.less'),
>   themeVariables: Objects.keys(themeVariables),
>   indexFileName: 'index.html',
>   outputFilePath: path.join(__dirname, './public/color.less'),
>   customColorRegexArray: [/^color\(.*\)$/]
> }
> ```

I have done this in my code. You can see it in my code
```
const themeVariables = Object.keys(lightTheme)
```

**Comment by mzohaibqc** [comment]
@hellomrbigshot Why do you want to use `@primary-1: color(~`colorPalette('@{primary-color}', 1) `);` where you can sue `@primary-color`

**Comment by hellomrbigshot** [comment]
> @hellomrbigshot Why do you want to use
> `` @primary-1: color(~`colorPalette('@{primary-color}', 1) `);* ``
> where you can sue `@primary-color`

I just want to change backgound of `.ant-select-item-option-selected`.

**Comment by hellomrbigshot** [comment]
> @hellomrbigshot Ok, got that since `@select-item-selected-bg: @primary-1` in ant design default theme variables but this is not the way to go. I've disabled theme variables ending with an integer like @primary-1, @Blue-1 etc since they represent a shade of base color like @primary-color so in order to keep it consistent, dependent shades like this can't be updated. You can simply updated the respective color `@select-item-selected-bg`, assign it a unique value in variables.less file and mention in `themevariables` in options
> 
> I hope you get my point and it will work for you.

It doen't work for me by updating `@select-item-selected-bg`，but it works for me by updating `@primary-color`. 
The problem was caused by `@link-color`. I upload a [demo](https://github.com/hellomrbigshot/theme-demo)
When i edit `@link-color` after `@primary-color`，`@primary-color` will be covered by `@link-color`. In [default.less](https://github.com/ant-design/ant-design/blob/master/components/style/themes/default.less) for antd, it shows
```
@link-color: @primary-color;
```
I never use less before does this mean if link-color changes, primary-color will change too?

**Comment by mzohaibqc** [comment]
@hellomrbigshot I release new version i.e. `antd-theme-generator@1.2.3` and respective webpack plugin `antd-theme-webpack-plugin@1.3.5` which includes some bug fixes and code improvements and reduced output `color.less` in size

Here is updated demo
https://mzohaibqc.github.io/antd-theme-generator/

code:
https://github.com/mzohaibqc/antd-theme-generator/tree/master/examples/customize-cra

**Comment by hellomrbigshot** [comment]
> @hellomrbigshot I release new version i.e. `antd-theme-generator@1.2.3` and respective webpack plugin `antd-theme-webpack-plugin@1.3.5` which includes some bug fixes and code improvements and reduced output `color.less` in size
> 
> Here is updated demo
> https://mzohaibqc.github.io/antd-theme-generator/
> 
> code:
> https://github.com/mzohaibqc/antd-theme-generator/tree/master/examples/customize-cra

thank you, i will update my dependencies
