### ISSUE TITLE
SyntaxError: Inline JavaScript is not enabled. Is it set in your options?

### ISSUE THREAD

**Issue by vreddy448** [mzohaibqc/antd-theme-generator#41]
SyntaxError: Inline JavaScript is not enabled. Is it set in your options?
in color.less on line 123, column 1:

122// https://github.com/ant-design/ant-motion/issues/44
123.bezierEasingMixin();

can you please help me to implement live theme capability for my application with antd component library

**Comment by mzohaibqc** [comment]
You need to allow run javascript in less-loader configurations. Read the docs how to setup ant design with create-react-app

https://ant.design/docs/react/use-with-create-react-app#Customize-Theme

```
const path = require("path");
const fs = require("fs");
const {
  override,
  fixBabelImports,
  addLessLoader,
  addWebpackPlugin,
} = require("customize-cra");
const { getThemeVariables } = require("antd/dist/theme");

module.exports = override(
  fixBabelImports("import", {
    libraryName: "antd",
    libraryDirectory: "es",
    style: true,
  }),
  addLessLoader({
    javascriptEnabled: true,
    modifyVars: getThemeVariables({
      '@primary-color': '#1DA57A'
    }),
  })
);
```

**Comment by xiaohuoni** [comment]
When using less@3+, this problem still exists.
```
lessLoader: {
    javascriptEnabled: true,
 },
```
When using less@2.7.2 a, it works.

**Comment by anuragguptanbmc** [comment]
@xiaohuoni  If the in the script tag you are using less version 3+ update your code like this
`    <script>
      window.less = {
        async: false,
        env: 'production',
        javascriptEnabled: true,
      };
    </script>
    <script type="text/javascript" src="${options.lessUrl}"></script>`
