### ISSUE TITLE
Antd for Angular does not recognize antdStylesFile path

### ISSUE THREAD

**Issue by cipchk** [mzohaibqc/antd-theme-generator#43]
https://github.com/mzohaibqc/antd-theme-generator/blob/master/index.js#L340

```
error Error: ENOENT: no such file or directory, open '/Users/cipchk/Desktop/work/delon/node_modules/ng-zorro-antd/dist/antd.less'
```

For antd for angular version `antd.less` should be `ng-zorro-antd.less`.

**Comment by mzohaibqc** [comment]
@cipchk Show you configurations and also show directory structure of `node_modules/ng-zorro-antd`

**Comment by cipchk** [comment]
@mzohaibqc https://unpkg.com/browse/ng-zorro-antd@9.1.2/

**Comment by mzohaibqc** [comment]
@cipchk which means that it will not work as it is but if can handle path assumptions and allow some parameter which will allow users to pass custom paths for `antd.less` which is `https://unpkg.com/browse/ng-zorro-antd@9.1.2/ng-zorro-antd.less` in this case then it will work without any logic change. However, I am not sure I'll able to add this change over the weekend or not. If you or someone else is willing to create a PR, most welcome. 

It will be resolved soon, at max, within 2 weeks
