### ISSUE TITLE
Why the checkbox and datepicker styles are incorrect?

### ISSUE THREAD

**Issue by pengxue-net** [mzohaibqc/antd-theme-generator#45]
Why does datepicker have borders?（为什么checkbox不显示√,datepicker有边框?）
![{8378BE51-E245-41D1-8C3F-93BC5426BB10}_20200603142144](https://user-images.githubusercontent.com/59425304/83602960-185b1d00-a5a6-11ea-85c1-8cbc2fb90a9a.jpg)
![{F153DDB8-3E30-463B-87FB-F55A13A71D48}_20200603142202](https://user-images.githubusercontent.com/59425304/83602967-1b560d80-a5a6-11ea-8580-72ad55b137d1.jpg)

**Comment by mzohaibqc** [comment]
@pengxue-net I've fixed the issue and published a new version of `antd-theme-generator@1.2.4`

Kindly update the package and it will be fixed

**Comment by pengxue-net** [comment]
@mzohaibqc 
I updated to version 1.2.4. The problem was solved, but the theme of the button was invalid. Version 1.2.2 is correct.

**Comment by mzohaibqc** [comment]
What do you mean by `The problem was solved, but the theme of the button was invalid.`?
I tested and it's working fine.

**Comment by pengxue-net** [comment]
@mzohaibqc 
The date and checkbox problems have been solved, but my current button theme cannot be switched
(日期和checkBox问题已解决，但是在1.2.4中button主题没有切换，@btn-primary-bg变量已修改，在1.2.2中button主题切换是有效的)

**Comment by mzohaibqc** [comment]
@pengxue-net I tested and it worked, it seems like your implementation issue. some custom style might be overriding your style

**Comment by pengxue-net** [comment]
@mzohaibqc 
我又重新测试了一遍，当调用 
window.less.modifyVars({
      '@primary-color': color,
      '@btn-primary-bg': color
 }) 
修改主题时，所有主题都能正确改变，但是这时候我F5刷新界面之后，button的主题并没有被覆盖，这种情况您测试到没有，在antd-theme-generator 1.2.4之前版本是不会出现这种情况，代码如下：

vars.less：
@import "~antd/lib/style/themes/default.less";
@primary-color: #2F54EB;
@link-color: #2F54EB;
@btn-primary-bg: #2F54EB;
:root { 
    --primaryColor: @primary-color;
 }

color.js：
const path = require('path');
const { generateTheme } = require('antd-theme-generator');

const options = {
    stylesDir: path.join(__dirname, './src/styles'),
    antDir: path.join(__dirname, './node_modules/antd'),
    varFile: path.join(__dirname, './src/styles/vars.less'),
    mainLessFile: path.join(__dirname, './src/styles/main.less'),
    themeVariables: [
        '@primary-color',
        '@btn-primary-bg',
        '@secondary-color',
        '@text-color',
        '@text-color-secondary',
        '@heading-color',
        '@layout-body-background',
        '@layout-header-background'
    ],
    indexFileName: 'index.html',
    outputFilePath: path.join(__dirname, './public/color.less'),
}

generateTheme(options).then(less => {
    console.log('Theme generated successfully');
}).catch(error => { console.log('Error', error); });
