### ISSUE TITLE
Breaks stats.json

### ISSUE THREAD

**Issue by NitroBAY** [mzohaibqc/antd-theme-generator#46]
The fact it console.log Theme generated successfully breaks stats.json as the first line of stats.json becomes "Theme generated successfully" which makes the JSON invalid.

**Comment by mzohaibqc** [comment]
@NitroBAY Do you think that I can help you after reading what you have written above? How I can know about your stats.json? How I can know what do you mean by "breaks stats.json"? Spend some time and learn how to report an issue.

Look at this issue, this is similar to your problem but he wrote the steps to reproduce and pasted the error
https://github.com/mzohaibqc/antd-theme-generator/issues/42
