### ISSUE TITLE
[Enhancement] Change `hashCache` to include theme variables. 

### ISSUE THREAD

**Issue by Jfelix61** [mzohaibqc/antd-theme-generator#48]
Before the issue, thanks for this amazing snippet! 

I am creating two different stylesheets based on the same style directory. One for dark theme and another for the light theme. The only difference they have is the theme variables and output directory. However, I cannot call the function again and generate a new less stylesheet since it returns the old `cssCache` because the styles folder routes have not changed. That is why it would be good to include a `themeVariables` for cache to avoid this.  

```
let content = `${JSON.stringify(themeVariables)} `;
   styles.forEach(filePath => {
     content += fs.readFileSync(filePath).toString();
  });  
```

P.S. What exactly is the license of this repository and are we allowed to use this code commercially? I would love it if it could be an OSS to create contributions.

**Comment by mzohaibqc** [comment]
@Jfelix61 I wanted to ask, did you find a way to re-run this script with different variables? If yes, share it with the community so others can fix this if this happens to them and if not, I can add required changes to re-run this even styles content is the same but variables have changed.

Or even we can add an additional optional parameter to re-run forcefully.

**Comment by Jfelix61** [comment]
I was able to run it by modifying the source directly. However, better just to add an additional parameter. 

Possible implementation:
```javascript
async function generateTheme ({
  antDir,
  antdStylesDir,
  stylesDir,
  varFile,
  outputFilePath,
  useCache = true,
  cssModules = false,
  themeVariables = ['@primary-color'],
  customColorRegexArray = []
}) {
  try {
  // ...

    const hashCode = hash.sha256().update(content).digest('hex');
    if (hashCode === hashCache && useCache) {
      return cssCache;
    }
  // ...
```
