### ISSUE TITLE
color.less has unexcepted value

### ISSUE THREAD

**Issue by OhYee** [mzohaibqc/antd-theme-generator#49]
**Describe the bug**
When I set themeVariables as all variables in dark.less, some values are unexcepted.

Using the code below, the `ant-tag-xxx` got the unexcepted value(backgroundcolor).
(Each run will have a different random unexcepted value of `ant-tag-xxx`)

Such as 
```less
.ant-tag-lime {color: #a0d911;background: color(~`colorPalette("@{table-header-filter-active-bg}", 1)`);border-color: #eaff8f;}
```

**Show your code**
```js
const fs = require('fs');
const path = require('path');
const { generateTheme, getLessVars, isValidColor } = require('antd-theme-generator');

var themes = {};
const files = fs.readdirSync(path.join(__dirname, './node_modules/antd/lib', 'style/themes'));
const reg = /(.*)\.less/;
files.map((file) => {
  const res = reg.exec(file);
  if (!!res && res[1] !== 'index') {
    const name = res[1];
    const filepath = path.join(__dirname, './node_modules/antd/lib', 'style/themes', file);
    themes[name] = getLessVars(filepath);
  }
});

const keys = Object.keys(themes.dark).filter((key) => {
  if (!isValidColor(themes.dark[key])) return false;
  console.log(themes.default[key], '\t', themes.dark[key]);
  return themes.default[key] != themes.dark[key];
});
console.log(keys);

args = {
  antDir: path.join(__dirname, './node_modules/antd'),
  antdStylesDir: undefined,
  stylesDir: path.join(__dirname, './theme'),
  //   varFile: path.join(__dirname, './theme/vars.less'),
  outputFilePath: path.join(__dirname, './color.less'),
  cssModules: false,
  themeVariables: keys,
  customColorRegexArray: [],
};
console.log(args);
generateTheme(args);
```

**Version**
1.2.4

**Comment by mzohaibqc** [comment]
Do you have commented this line in your code
> //   varFile: path.join(__dirname, './theme/vars.less'),

`varFile` is required and it affects generated color.less

**Comment by OhYee** [comment]
`./theme/vars.less` is just one line
```less
@import '../node_modules/antd/lib/style/themes/default.less';
```

This is just a demo for reproducing. And whether `varFile` is commented or not, the result is still problematic

**Comment by mzohaibqc** [comment]
@OhYee You did not get my point. In your issue description, you have shown this configurations
```
args = {
  antDir: path.join(__dirname, './node_modules/antd'),
  antdStylesDir: undefined,
  stylesDir: path.join(__dirname, './theme'),
  //   varFile: path.join(__dirname, './theme/vars.less'),
  outputFilePath: path.join(__dirname, './color.less'),
  cssModules: false,
  themeVariables: keys,
  customColorRegexArray: [],
};
```

In this code block, `varFile` parameter is commented. This should not be commented.

**Comment by OhYee** [comment]
I'm sorry that In testing how to reproduce the problem, I forgot to restore the commented line.
I modified the code to look like the following, but the problem remains unresolved.

```js
args = {
  antDir: path.join(__dirname, './node_modules/antd'),
  antdStylesDir: undefined,
  stylesDir: path.join(__dirname, './theme'),
  varFile: path.join(__dirname, './theme/vars.less'),

  outputFilePath: path.join(__dirname, './color.less'),
  cssModules: false,
  themeVariables: keys,
  customColorRegexArray: [],
};
```

The antd-theme-generator does a pretty good job of implementing dynamic themes, with the only problem being that after implementing theme switches, the tag component has strange colors (which was not the case in earlier versions of Ant Design). Any ideas on how to solve this?

Thank you for taking the time to reply

**Comment by mzohaibqc** [comment]
@OhYee Just create a github project and reproduce your issue. I'll clone and will look into this.

**Comment by OhYee** [comment]
I have created the project. Thanks for your help.

https://github.com/OhYee/reproduce/tree/master/antd-theme-generator

**Comment by jijigo** [comment]
also have this issue!

**Comment by edison-tianhe** [comment]
The current version is 1.2.11, which also has this problem.
However, it is not necessary, and occasionally there is a problem with style confusion
bad
![image](https://user-images.githubusercontent.com/35984031/185888701-f4e27919-5457-4ed0-b80f-b8536059dec7.png)
good
![image](https://user-images.githubusercontent.com/35984031/185888776-75de2e10-28b5-4f66-a316-7dba1e23c2fb.png)
