### ISSUE TITLE
doesnt support bug support

### ISSUE THREAD

**Issue by amirjr1378** [mzohaibqc/antd-theme-generator#63]
**Describe the bug**
i want to chante @font-family variable too but my variable is gotten override.

**Show your code**
Show your `config-overrides.js` file and styles folder structure

**Screenshots**
![image](https://user-images.githubusercontent.com/49060396/96361531-6460c580-1133-11eb-843a-9974d8e28d5e.png)
![image](https://user-images.githubusercontent.com/49060396/96361538-6c206a00-1133-11eb-8470-dd8f6769d109.png)

**Version**
Which version is installed in your application? Try using the latest version, that may help
latest verison is installed

**Comment by mzohaibqc** [comment]
This package is only for color related theme/variables and does not support dynamic font.
