### ISSUE TITLE
Borders showing in Button type="link"

### ISSUE THREAD

**Issue by jotamodesto** [mzohaibqc/antd-theme-generator#64]
**Describe the bug**
Borders are showing on Button type="link" when it shouldn't. As shown in screenshots
This happened when I upgraded the antd-theme-webpack-plugin to 1.3.7.
I tried to revert the package version of the plugin to 1.3.6 but reinstalling the package using npm/yarn installed the 1.2.7 of antd-theme-generator.
I had to revert my yarn.lock to use the previous version and it worked just fine.
I openned the issue here, since it concerns more to the generator than the plugin I suppose.

**Show your code**
![image](https://user-images.githubusercontent.com/8514309/96635239-fa424f00-12f1-11eb-8467-2989745788fe.png)
![image](https://user-images.githubusercontent.com/8514309/96635319-1645f080-12f2-11eb-899a-41de2a4b5323.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/8514309/96633982-3d9bbe00-12f0-11eb-9113-d81dbe78ed2f.png)
![image](https://user-images.githubusercontent.com/8514309/96634823-6a040a00-12f1-11eb-9e93-ba887a54d6c8.png)

**Version**
1.2.7

**Comment by mzohaibqc** [comment]
@jotamodesto Fixed this issue, update antd-theme-generator and antd-theme-webpack-plugin version to latest which ever you are using

antd-theme-generator@1.2.8
and-theme-webpack-plugin@1.3.8

### Note: and-theme-webpack-plugin uses antd-theme-generator internally and it juest provides webpack syntax for plugin to be used as webpack plugin
