### ISSUE TITLE
Override a non-color variable not working.

### ISSUE THREAD

**Issue by david-soyez** [mzohaibqc/antd-theme-generator#72]
**Describe the bug**
This is my variables.less file, i'm changing ant variable @menu-item-padding
I understand that this script only extract colors but I can't even override a ant design padding variable. It seems that it's ignored or overwritten by this script.

**Show your code**
```
@import "~antd/lib/style/themes/default.less";
@menu-item-padding: 0 24px;
```

**Comment by mzohaibqc** [comment]
@david-soyez you need to pass that variable to less loader to override ant design padding when it will compile less files. You different  file for dynamic theme (let's say theme.less) and only add color related variables there and pass this file path as variables file in antd-theme-generator config object.

**Comment by david-soyez** [comment]
Thanks a lot it worked! i wasted a day trying to fix that.

fyi here is the code:

```
plugin: CracoLessPlugin,
      options: {
        lessLoaderOptions: {
          lessOptions: {
            modifyVars: {
              hack: `true;@import "${require.resolve('./src/assets/antd/variables.less')}";`
            },
            javascriptEnabled: true
          }
        }
      }
```
