### ISSUE TITLE
error on such 'background:url(./image/test.svg)'

### ISSUE THREAD

**Issue by Dpy0407** [mzohaibqc/antd-theme-generator#8]
For webpack result (config the image resource to outputDir), the compile result will be 'background:url(outputDir/image/test.svg)' & webpack will copy the image resource to the outputDir, it will work well.
But for 'antd-theme-generator', its result will be 'background:url(image/test.svg)' , but the test.svg be put in outPutDir by webpack, so this url will work wrong.
I think if is better to ignore this situation when background is a url resource? Briefly, once antd-theme-generator find the background is a url, just ignore, don't generator this part?

**Comment by mzohaibqc** [comment]
@Dpy0407 Update to latest version and it will be fixed. At the time of writing, it is  `antd-theme-generator@1.1.6`

**Comment by exvu** [comment]
@Dpy0407 Have you solved this problem?

**Comment by Dpy0407** [comment]
@exvu  sorry, I am working on another project now, So, I am not sure if the problem has been solved. maybe you can have a try, as @mzohaibqc said that it has been solved after version @1.1.6

**Comment by lPaths** [comment]
problem still there, I'm using `antd-theme-generator@^1.1.7`

**Comment by jokingzhang** [comment]
problem still there, I'm using antd-theme-generator@^1.1.9

**Comment by andylidong** [comment]
In the reduceplugin method, you can add the following code：

![image](https://user-images.githubusercontent.com/18454971/79952589-3c0e4c00-84ad-11ea-964f-eda858cc900e.png)

**Comment by mzohaibqc** [comment]
@Dpy0407 @exvu @lPaths @jokingzhang 

This issue has been resolved and package version has been updated
use `antd-theme-generator@1.2.0` in order to fix this issue

If you are using `[antd-theme-webpack-plugin](https://github.com/mzohaibqc/antd-theme-webpack-plugin)` then you need to use version `1.3.2`

Thanks a lot, @andylidong for this solution.
