### ISSUE TITLE
variables defined as hsv(n,n,n) format can not be customized 

### ISSUE THREAD

**Issue by wangmengHB** [mzohaibqc/antd-theme-generator#9]
For Example: the below variables are not in the mappings:
'@border-color-base',
'@background-color-light',
'@border-color-split',
'@input-placeholder-color',
So you can not use less.modifyVars to change theme instantly.

**Comment by wangmengHB** [comment]
@mzohaibqc  Not Match.
hsv is not considered as a valid color.
`/*
  This function takes color string as input and return true if string is a valid color otherwise returns false.
  e.g.
  isValidColor('#ffffff'); //true
  isValidColor('#fff'); //true 
  isValidColor('rgba(0, 0, 0, 0.5)'); //true
  isValidColor('20px'); //false
*/`

**Comment by mzohaibqc** [comment]
I'll fix this soon but any PR is welcome

**Comment by mzohaibqc** [comment]
@wangmengHB Is `hsv(n, n, n)` is a valid format for color in css? From this, it seems it's invalid https://www.w3schools.com/cssref/css_colors_legal.asp

**Comment by wangmengHB** [comment]
@mzohaibqc 
I know hsv(n, n, n) is not a valid format for color in css. 
The point is that, in ant design official site, it says it support to customize '@border-color-base'.
But actually it does not support to customize it dynamically with antd-theme-generator.
(https://ant.design/docs/react/customize-theme-cn#Ant-Design-%E7%9A%84%E6%A0%B7%E5%BC%8F%E5%8F%98%E9%87%8F).
The root cause is that:
in "components/style/themes/default.less":  @border-color-base      : hsv(0, 0, 85%); 
And hsv is not considered as a valid color in "antd-theme-generator".

My point is no matter hsv is valid color format or not, it is better to support customizing "@border-color-base'."

**Comment by mzohaibqc** [comment]
@wangmengHB Thanks for clarification, I'll fix this very soon

**Comment by mzohaibqc** [comment]
@wangmengHB I've fixed this issue and updated npm package `antd-theme-generator@1.1.4` and also webpack plugin to `antd-theme-webpack-plugin@1.1.9`.
Don't forget to ⭐ ⭐ ⭐ :)

**Comment by wangmengHB** [comment]
@mzohaibqc I check it. It is fixed. Thanks.
